### ISSUE TITLE
[backend] position ID missing for route `admin/positions`

### ISSUE THREAD

**Issue by Accelsnow** [uoft-tapp/tapp#479]
For route admin/positions (POST), the API document states the schema as:

```
{
  "position_code": "string",
  "position_title": "string",
  "hours_per_assignment": 0,
  "start_date": "string",
  "end_date": "string",
  "duties": "string",
  "qualifications": "string",
  "ad_hours_per_assignment": 0,
  "ad_num_assignments": 0,
  "ad_open_date": "string",
  "ad_close_date": "string",
  "desired_num_assignments": 0,
  "current_enrollment": 0,
  "current_waitlisted": 0,
  "instructor_ids": [
    0,
    "string"
  ],
  "instructor_preference": [
    {
      "preference_level": 0
    }
  ]
}
```

which does not include an id field. This is understandable since we may be adding new positions and the client may have no way to determine a good position id. However, in the controller used by this route `backend/app/controllers/api/v1/admin/positions_controller.rb`, there is a `before_action :find_position`, which calls the following function to find a position object 

```
def find_position
        @position = Position.find(params[:id])
    end
```

In this case, the API call for adding a new position always throws an error, since there is no id field in the schema.

The error stack on the backend docker image:

```
Started POST "/api/v1/admin/positions" for 172.28.0.1 at 2021-01-21 19:31:23 +0000
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 54], ["LIMIT", 1]]
  ↳ app/services/active_user_service.rb:36:in `active_user'
Processing by Api::V1::Admin::PositionsController#create as */*
  Parameters: {"position_code"=>"CSC494", "position_title"=>"Capstone Project", "hours_per_assignment"=>0, "start_date"=>"test start date", "end_date"=>"test end date", "duties"=>"test duty", "qualifications"=>"test qualification", "ad_hours_per_assignment"=>0, "ad_num_assignments"=>0, "ad_open_date"=>"test date", "ad_close_date"=>"test date", "desired_num_assignments"=>0, "current_enrollment"=>0, "current_waitlisted"=>0, "instructor_ids"=>[0, "test id"], "instructor_preference"=>[{"preference_level"=>0}]}
ERROR: Couldn't find Position without an ID
Couldn't find Position without an ID
Traceback:
	/controllers/api/v1/admin/positions_controller.rb:43:in `find_position'
[active_model_serializers] Rendered ActiveModel::Serializer::Null with Hash (0.05ms)
Completed 200 OK in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 1609)
```

and postman response body:

```
{
    "status": "error",
    "message": "Couldn't find Position without an ID",
    "payload": {}
}
```

**Comment by Accelsnow** [comment]
This issue is no longer valid after the discussion of how the authentication module and API document work.
